menu_title: '&1&l功能菜单&f&l（&e/settings&f&l）'
open_command: settings
permission: settings.open
size: 26
items:
  'ITEM_SLOT_0':
    material: white_stained_glass_pane
    slots: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    display_name: '&f&l装饰物品'
  'ITEM_SLOT_1':
    material: light_blue_stained_glass_pane
    slots: 
    - 10
    - 12
    - 14
    - 16
    display_name: '&f&l装饰物品'
  'SCOREBOARD':
    material: apple
    slot: 11
    display_name: '&f&l开关计分板'
    lore:
    - '&e&l开关计分板:D'
    left_click_commands:
    - '[player] sb toggle'
    right_click_commands:
    - '[player] sb toggle'
  'RESOURCESPACK':
    material: chest
    slot: 13
    display_name: '&f&l打开服务器资源包菜单'
    lore:
    - '&e&l服务器专用资源包设置:D'
    left_click_commands:
    - '[player] dm open resourcepack'
    - '[close]'
    right_click_commands:
    - '[player] dm open resourcepack'
    - '[close]'
  'ABTOGGLE':
    material: golden_apple
    slot: 15
    display_name: '&f&l开关技能状态显示栏'
    lore:
    - '&e&l开关技能状态显示栏:D'
    left_click_commands:
    - '[player] abtoggle'
    right_click_commands:
    - '[player] abtoggle'


    